version: "3"

services:
  server:
    container_name: server_nodebr
    build:
      context: ./module-12
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - mongodb
    ports:
      - 3333:3333
    volumes:
      - ./module-12:/usr/app
      - /usr/app/node_modules
    env_file:
      - ./module-12/config/.env.dev
    command: sh -c "npm run test:dev"

  postgres:
    container_name: postgres_nodebr
    image: postgres:alpine
    environment:
      POSTGRES_DB: heroes
      POSTGRES_USER: lucasfranca
      POSTGRES_PASSWORD: lucasfranca
    ports: 
      - 5432:5432

  adminer:
    container_name: adminer_nodebr
    image: adminer
    ports:
      - 8080:8080
    links:
      - postgres

  mongodb:
    container_name: mongodb_nodebr
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017

  mongoclient:
    container_name: mongoclient_nodebr
    image: mongoclient/mongoclient
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - mongodb