version: "3"

services:
  server:
    container_name: cursonodebr_server
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - mongodb
    ports:
      - 3333:3333
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    env_file:
      - ./server/config/.env.dev
    command: sh -c "npm t && npm run test:dev"

  postgres:
    container_name: cursonodebr_postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: heroes
      POSTGRES_USER: lucasfranca
      POSTGRES_PASSWORD: lucasfranca
    ports: 
      - 5432:5432

  adminer:
    container_name: cursonodebr_adminer
    image: adminer
    ports:
      - 8080:8080
    links:
      - postgres

  mongodb:
    container_name: cursonodebr_mongodb
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017

  mongoclient:
    container_name: cursonodebr_mongoclient
    image: mongoclient/mongoclient
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - mongodb